<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<title>Free CSS template by ChocoTemplates.com</title>
	<link rel="stylesheet" href="css/style.css" type="text/css" media="all" />
	<!--[if IE]>
		<style type="text/css" media="screen">
			.shell {background-image: none;filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='css/images/shell-bg.png', sizingMethod='scale');}
			.box{background-image: none;filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='css/images/dot.png', sizingMethod='scale');}
			.transparent-frame .frame{background-image: none;filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(src='css/images/transparent-frame.png', sizingMethod='image');}
			.search .field{padding-bottom:9px}
		</style>
	<![endif]-->
	<script src="js/jquery-1.3.2.min.js" type="text/javascript"></script>
	<script src="js/jquery-func.js" type="text/javascript"></script>
</head>
<body>

<!-- Shell -->
<div class="shell">
	
	<!-- Header -->
	<div id="header">
		<!-- Logo -->
		<h1 id="logo"><a href="#">autoportal your friend on the road</a></h1>
		<!-- End Logo -->
		
		<!-- Navigation -->
		<div id="nav">
			<ul>
			    <li><a class="active" href="#">Home</a></li>
			    <li><a href="#">News</a></li>
			    <li><a href="#">Reviews</a></li>
			    <li><a href="#">Tuning</a></li>
			    <li><a href="#">Gallery</a></li>
			    <li><a href="#">Community</a></li>
			</ul>
		</div>
		<!-- End Navigation -->
		
	</div>
	<!-- End Header -->
	
	
	<!-- Content -->
	<div id="content">
		
		<!-- Sidebar -->
		<div id="sidebar">
			
			<!-- Search -->
			<form action="" class="search" method="post">
				<div class="cl">&nbsp;</div>
				<input type="text" class="field blink" value="search" title="search" />
				<div class="btnp"><input type="submit" value="go" /></div>
				<div class="cl">&nbsp;</div>
			</form>
			<!-- End Search -->
			
			<!-- Sign In Links -->
			<div class="links">
				<div class="cl">&nbsp;</div>
				<a href="#" class="left">Sign In</a>
				<a href="#" class="right">Create account</a>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Sign In Links -->
			
			<!-- Box Latest News -->
			<div class="box">
				<h2>Latest News</h2>
				<ul>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb1.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Lorem ipsum dolo</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb2.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Dolor amet urna isque</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb3.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Molestie id sceler leo</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb4.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Sed elementum molesti</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				</ul>
				<a href="#" class="up">See more</a>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Box Latest News -->
			
			<!-- Box Latest Reviews -->
			<div class="box">
				<h2>Latest Reviews</h2>
				<ul>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb5.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Lorem ipsum dolo</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb6.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Dolor amet urna isque</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb7.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Molestie id sceler leo</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/thumb8.jpg" alt="" /></a>
				    	<div class="info">
					    	<h5><a href="#">Sed elementum molesti</a></h5>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				</ul>
				<a href="#" class="up">See more</a>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Box Latest Reviews -->
			
			<!-- Box Latest Posts -->
			<div class="box">
				<h2>Latest Posts</h2>
				<ul>
				    <li>
				    	<h5><a href="#">Lorem ipsum dolo</a></h5>
				    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
				    </li>
				    <li>
				    	<h5><a href="#">Dolor amet urna isque</a></h5>
				    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
				    </li>
				    <li>
				    	<h5><a href="#">Molestie id sceler leo</a></h5>
				    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
				    </li>
				    <li>
				    	<h5><a href="#">Sed elementum molesti</a></h5>
				    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
				    </li>
				    <li>
				    	<h5><a href="#">Sed elementum molesti</a></h5>
				    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo </p>
				    </li>
				</ul>
				<a href="#" class="up">See more</a>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Box Latest Posts -->
			
		</div>
		<!-- End Sidebar -->
		
		
		<!-- Main -->
		<div id="main">
			
			<!-- Top Image -->
			<ul class="navigate">
			    <li class="active"><a href="#">1</a></li>
			    <li><a href="#">2</a></li>
			    <li><a href="#">3</a></li>
			    <li><a href="#">4</a></li>
			    <li><a href="#">5</a></li>
			    <li><a href="#">6</a></li>
			</ul>
			<div class="transparent-frame">
				<div class="frame">&nbsp;</div>
				<img src="css/images/sls.jpg" alt="" />
			</div>
			<div class="cl">&nbsp;</div>
			<!-- End Top Image -->
			
			
			<!-- Box -->
			<div class="box">
				<h2>Tuning</h2>
				<ul class="line">
				    <li>
				    	<a class="frm" href="#"><img src="css/images/car1.jpg" alt="" /></a>
				    	<a href="#">Sed elementum molesti</a>
		    		</li>
		    		<li>
				    	<a class="frm" href="#"><img src="css/images/car2.jpg" alt="" /></a>
				    	<a href="#">Dolor amet urna isque</a>
		    		</li>
		    		<li>
				    	<a class="frm" href="#"><img src="css/images/car3.jpg" alt="" /></a>
				    	<a href="#">Lorem ipsum dolo</a>
		    		</li>
				</ul>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Box -->
			
			<!-- Box -->
			<div class="box">
				<h2>Editor's Pick</h2>
				<ul>
				    <li>
				    	<a href="#" class="image"><img src="css/images/car4.jpg" alt="" /></a>
				    	<div class="info">
					    	<h4><a href="#">Dolor amet urna isque</a></h4>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna.</p>
					    	<a class="up">read more</a>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/car5.jpg" alt="" /></a>
				    	<div class="info">
					    	<h4><a href="#">Lorem dolor consectetur elit.</a></h4>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna.</p>
					    	<a class="up">read more</a>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/car6.jpg" alt="" /></a>
				    	<div class="info">
					    	<h4><a href="#">Sed elementum molestie urna</a></h4>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna.</p>
					    	<a class="up">read more</a>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				    <li>
				    	<a href="#" class="image"><img src="css/images/car7.jpg" alt="" /></a>
				    	<div class="info">
					    	<h4><a href="#">Tincidunt conimentum ipsum</a></h4>
					    	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna, id scelerisque leo sodales sit amet. Curabitur volutpat lorem euismod nunc tincidunt condimentum.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed elementum molestie urna.</p>
					    	<a class="up">read more</a>
					    </div>	
				    	<div class="cl">&nbsp;</div>
				    </li>
				</ul>
				<a href="#" class="up">See more</a>
				<div class="cl">&nbsp;</div>
			</div>
			<!-- End Box -->
			
		</div>
		<!-- End Main -->
		
		<div class="cl">&nbsp;</div>
	</div>
	<!-- End Content -->
	
	<!-- Footer -->
	<div id="footer">
		<p>&copy; Sitename.com. Design by <a href="http://chocotemplates.com">ChocoTemplates.com</a></p>
	</div>
	<!-- End Footer -->
</div>
<!-- End Shell -->
</body>
</html>