<form action="" method="post">
<table width="300" border="0">
<tr><td colspan="2">Ingrese su clave y contraseña</td></tr>
<tr><td>Usuario:</td><td><input type="text" size="20"  name="username"/></td></tr>
<tr><td>Clave</td><td><input type="password" size="20" name="password"/></td></tr>
<tr><td colspan="2"><input type="submit" size="20" value="Ingresar"/></td></tr>
</table>
<h1><?php echo $message;?></h1>
</form>

