<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="es-ES" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
    <head>
        <?php echo $this->headTitle("Smeagol CMS"); ?>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/themes/enterprise/css/style.css'); ?>
        <!--[if IE 6]>
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/themes/enterprise/css/ie6.css'); ?>
        <![endif]-->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/themes/enterprise/js/jquery-1.4.2.js'); ?>
        <script src="/themes/enterprise/js/jquery.jcarousel.js" type="text/javascript"></script>
        <script src="/themes/enterprise/js/jquery.pngFix.js" type="text/javascript"></script>
        <script src="/themes/enterprise/js/js-fnc.js" type="text/javascript"></script>
    </head>
    <body>

        <!-- Shell -->
        <div class="shell">

            <!-- Header -->
            <div id="header">

                <h1 id="logo"><a href="#" title="free website css template">COMPANY NAME HERE<span>FREE WEBSITE TEMPLATE</span></a></h1>

                <div id="navigation">
                    <ul>
                        <li><a href="<?php echo $this->basePath(); ?>/" class="active" title="Inicio"><span>Inicio</span></a></li>
                        <li><a href="<?php echo $this->basePath(); ?>/page/nosotros" title="Nosotros"><span>Nosotros</span></a></li>
                        <li><a href="<?php echo $this->basePath(); ?>/page/servicios" title="Servicios"><span>Servicios</span></a></li>
                        <li><a href="<?php echo $this->basePath(); ?>/page/soluciones" title="Soluciones"><span>Soluciones</span></a></li>
                        <li><a href="<?php echo $this->basePath(); ?>/page/soporte" title="Soporte"><span>Soporte</span></a></li>
                        <li><a href="<?php echo $this->basePath(); ?>/page/contactenos" title="Contáctenos"><span>Contáctenos</span></a></li>
                        <?php if ($is_login) { ?>
                            <li><a href="<?php echo $this->basePath(); ?>/auth" title="Login"><span>Login</span></a></li>
                        <?php } else { ?>		    
                            <li><a href="<?php echo $this->basePath(); ?>/logout" title="Login"><span>Logout</span></a></li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
            <!-- End Header -->
            <?php echo $this->content; ?>	
        </div>
        <!-- End Shell -->
        <!-- Footer -->
        <div id="footer">
            <div class="shell">
                <p class="left">

                    <a href="<?php echo $this->basePath(); ?>/index" title="Inicio" >Inicio</a>
                    <span>|</span>
                    <a href="<?php echo $this->basePath(); ?>/page/nosotros" title="Nosotros">Nosotros</a>
                    <span>|</span>
                    <a href="<?php echo $this->basePath(); ?>/page/servicios" title="Servicios">Servicios</a>
                    <span>|</span>
                    <a href="<?php echo $this->basePath(); ?>/page/soluciones" title="Soluciones">Soluciones</a>
                    <span>|</span>
                    <a href="<?php echo $this->basePath(); ?>/page/soporte" title="Soporte">Soporte</a>
                    <span>|</span>
                    <a href="<?php echo $this->basePath(); ?>/page/contactenos" title="Contáctenos">Contáctenos</a>
                    <span>|</span>

                </p>

                <p class="right">
                    &copy; Sitename.com. Design by <a href="http://css-free-templates.com/" title="Free Website Templates">CSS-Free-Templates</a>
                </p>

                <div class="cl">&nbsp;</div>
            </div>
        </div>	
        <!-- End Footer -->

    </body>
</html>