<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="es-ES" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
    <head>
        <?php echo $this->headTitle("Smeagol CMS"); ?>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/themes/enterprise/css/style.css'); ?>
        <!--[if IE 6]>
        <?php echo $this->headLink()->prependStylesheet($this->basePath() . '/themes/enterprise/css/ie6.css'); ?>
        <![endif]-->
        <?php if ($is_login) { ?>
            <?php echo $this->headLink()->appendStylesheet($this->basePath() . '/admin/css/admin-style.css'); ?>
            <?php } ?>
            <?php if ($is_front) { ?>
                <?php echo $this->headScript()->prependFile($this->basePath() . '/themes/enterprise/js/jquery-1.4.2.js'); ?>
                <script src="/themes/enterprise/js/jquery.jcarousel.js" type="text/javascript"></script>
                <script src="/themes/enterprise/js/jquery.pngFix.js" type="text/javascript"></script>
                <script src="/themes/enterprise/js/js-fnc.js" type="text/javascript"></script>
            <?php } else { ?>
                <?php echo $this->headScript()->prependFile($this->basePath() . '/jquery-1.11.1.min.js'); ?>
            <?php } ?>
        </head>
        <body>

            <!-- Shell -->
            <div class="shell">
                <!-- Header -->
                <div id="header">	
                    <?php if ($is_login) { ?>
                        <div id="menu_div">
                            <div id="navigation-admin">   
                                <div id="menu">
                                    <?php echo $this->navigation("admin_menus")->menu(); ?>
                                </div>
                            </div>
                        </div>
                    <?php } ?>      

                    <h1 id="logo"><a href="#" title="free website css template">SMEAGOL INC<span>FREE WEBSITE TEMPLATE</span></a></h1>
                    <div id="login">
                        <?php if (!$is_login) { ?>                     
                            <a href="<?php echo $this->basePath(); ?>/login" title="Login"><span>Login</span></a>
                        <?php } else { ?>                
                            <a href="<?php echo $this->basePath(); ?>/logout" title="Logout"><span>Logout</span></a>
                        <?php } ?>
                    </div>		
                    <br/><br/>
                    <div id="navigation">   
                        <?php echo $this->navigation("primary_menus")->menu(); ?>
                    </div>
                </div>
                <!-- End Header -->
                <div id="content">
                 <?php if(!$is_front){?>
                    <br/><br/><br/><br/>
                 <?php } ?>   
                 <?php echo $this->content; ?>
                </div>
            </div>
            <!-- End Shell -->
            <!-- Footer -->
            <div id="footer">
                <div class="shell">
                    <p class="left">

                        <a href="<?php echo $this->basePath(); ?>/index" title="Inicio" >Inicio</a>
                        <span>|</span>
                        <a href="<?php echo $this->basePath(); ?>/page/nosotros" title="Nosotros">Nosotros</a>
                        <span>|</span>
                        <a href="<?php echo $this->basePath(); ?>/page/servicios" title="Servicios">Servicios</a>
                        <span>|</span>
                        <a href="<?php echo $this->basePath(); ?>/page/soluciones" title="Soluciones">Soluciones</a>
                        <span>|</span>
                        <a href="<?php echo $this->basePath(); ?>/page/soporte" title="Soporte">Soporte</a>
                        <span>|</span>
                        <a href="<?php echo $this->basePath(); ?>/page/contactenos" title="Contáctenos">Contáctenos</a>
                    <span>|</span>

                </p>

                <p class="right">
                    &copy; Sitename.com. Design by <a href="http://css-free-templates.com/" title="Free Website Templates">CSS-Free-Templates</a>
                </p>

                <div class="cl">&nbsp;</div>
            </div>
        </div>	
        <!-- End Footer -->

    </body>
</html>
