<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="es-ES" xmlns="http://www.w3.org/1999/xhtml" dir="ltr">
<head>
	<?php echo $this->headTitle("Smeagol CMS");?>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
	<?php echo $this->headLink();?>
	<?php echo $this->headScript();?>
</head>
<body>
<?php echo $this->content; ?>	
</body>
</html>