<!-- Slider -->
<div id="slider">
    <a href="#" id="prev" class="notext">prev</a>
    <a href="#" id="next" class="notext">next</a>

    <div id="slider-content">
        <ul>
            <li>
                <div class="left-side">
                    <img src="/mac-image.png" alt="" />
                </div>

                <div class="right-side">
                    <h2>free simple template</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <strong>Aliquam</strong> sed fringilla arcu.<a href="#" title="Free Website Templates">Maecenas</a> sit amet cursus augue. <a href="#" title="Free Website Templates">Donec</a> felis eros, luctus at blandit ac.</p>

                    <a href="#" class="get-started notext">get started - lets talk about your project</a>	
                </div>

                <div class="cl">&nbsp;</div>
            </li>
            <li>
                <div class="left-side">
                    <img src="/mac-image.png" alt="" />
                </div>

                <div class="right-side">
                    <h2>free simple template</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <strong>Aliquam</strong> sed fringilla arcu.<a href="#" title="Free Website Templates">Maecenas</a> sit amet cursus augue. <a href="#" title="Free Website Templates">Donec</a> felis eros, luctus at blandit ac.</p>

                    <a href="#" class="get-started notext">get started - lets talk about your project</a>	
                </div>

                <div class="cl">&nbsp;</div>
            </li>
            <li>
                <div class="left-side">
                    <img src="/mac-image.png" alt="" />
                </div>

                <div class="right-side">
                    <h2>free simple template</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <strong>Aliquam</strong> sed fringilla arcu.<a href="#" title="Free Website Templates">Maecenas</a> sit amet cursus augue. <a href="#" title="Free Website Templates">Donec</a> felis eros, luctus at blandit ac.</p>

                    <a href="#" class="get-started notext">get started - lets talk about your project</a>	
                </div>

                <div class="cl">&nbsp;</div>
            </li>
        </ul>
    </div>
</div>
<!-- End Slider -->

<!-- Main -->
<div id="main">
    <div class="cols">
        <div class="col">
            <div class="post">
                <h3>What is Mondays?</h3>
                <img src="/monitor.gif" alt="" class="right" />
                <p><strong>Lorem ipsum dolor</strong> sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <strong>Aliquam</strong> sed frin gilla arcu. Maecenas sit amet cursus augue. Donec felis eros, <a href="#" title="Free Website Templates">luctus</a> at blandit ac.</p>
                <div class="cl">&nbsp;</div>
                <a href="#" title="Free Website Templates" class="learn-more" >Learn more</a>
            </div>
        </div>

        <div class="col">
            <div class="post">
                <h3>Monday Services</h3>
                <img src="/gears.gif" alt="" class="right" />
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <strong>Aliquam</strong> sed frin gilla arcu. Maecenas sit amet cursus augue. Donec felis eros, <a href="#" title="Free Website Templates">luctus at blandit</a> ac.</p>
                <div class="cl">&nbsp;</div>
                <a href="#" title="Free Website Templates" class="learn-more">Learn more</a>
            </div>
        </div>

        <div class="col col-last">
            <div class="post">
                <h3>Monday Support</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. Aliquam sed fringilla arcu. <strong>Maecenas</strong> sit amet cursus augue. Donec felis eros, luctus at blandit ac. Nunc ornare <span class="underline">consequat</span> tortor quis porttitor.</p>
                <a href="#" title="Free Website Templates" class="learn-more">Learn more</a>
            </div>
        </div>

        <div class="cl">&nbsp;</div>
    </div>

    <div id="content">

        <div class="col">
            <div class="post">
                <h3>Why Mondays?</h3>
                <img src="/mac.gif" alt="" class="right"/>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc <a href="#" title="Free Website Templates">ornare</a>ornare consequat tortor quis porttitor. Aliquam sed fringilla arcu. Maecenas sit amet <strong>cursus</strong> augue. Donec felis eros, luctus at blandit ac.</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ornare consequat tortor quis porttitor. <span class="underline">Aliquam</span> sed fringilla arcu. </p>
                <a href="#" title="Free Website Templates" class="learn-more">Learn more</a>
            </div>
        </div>

        <div class="col col-last">
            <div class="post">
                <h3>Noticias</h3>
                <?php foreach ($noticias as $new) : ?>
                    <p><a href="<?php echo $this->escapeHtml($new->url); ?>"><?php echo $this->escapeHtml($new->title); ?></a></p>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="cl"></div>

    </div>
</div>
<!-- End Main -->